export const data = {
  skills: [
    'Javascript',
    'Typescript',
    'Node.js',
    'NestJS',
    'Fastify',
    'Prisma ORM',
    'React',
    'Next.js',
    'React Native',
    'Expo',
    'PHP',
    'Laravel',
    'Blade',
    'WordPress',
    'Bedrock',
    'Sage',
    'MySQL',
    'Postgres',
    'Docker',
    'Storybook',
    'Tailwind',
    'Boostrap',
    'Styled Components',
  ],
}
