export const data = {
  skills: [
    'Inteligência Artificial',
    'Javascript',
    'Typescript',
    'Node.js',
    'NestJS',
    'Fastify',
    'Express',
    'Prisma ORM',
    'Drizzle ORM',
    'React',
    'Next.js',
    'React Native',
    'Expo',
    'PHP',
    'Laravel',
    'Blade',
    'WordPress',
    'Bedrock',
    'Sage',
    'MySQL',
    'Postgres',
    'Docker',
    'Storybook',
    'Tailwind',
    'Bootstrap',
    'Styled Components',
    'AWS',
  ],
}
